### ISSUE TITLE
Entrevista 

### ISSUE THREAD

**Issue by Daisy-GonzalezLita12** [SistemasTecTlaxiaco/actividad-7-practica-de-entrevista-equipo_tec#1]
[Practica_7_Daisy_Maribel_Adriana_Fundamentos_Ing_Software.pdf](https://github.com/user-attachments/files/17563650/Practica_7_Daisy_Maribel_Adriana_Fundamentos_Ing_Software.pdf)

**Comment by Blanca-estela-valerio-rivero** [comment]
De a cuerdo a la rubrica tiene 28%

**Comment by josealfredo79** [comment]
Bien hecho y revisado...
